name: Raising JIRA issues for Dependabot alerts

on:
  schedule:
    - cron: '* * * * *'

jobs:
  syncSecurityAlerts:
    runs-on: ubuntu-latest
    steps:
      - name: "Sync security alerts to Jira issues"
        uses: reload/github-security-jira@v1.3.1
        env:
          GH_SECURITY_TOKEN: ${{ secrets.GitHubSecurityToken }}
          JIRA_TOKEN: ${{ secrets.JiraApiToken }}
          JIRA_HOST: https://cruzeaakash.atlassian.net
          JIRA_USER: aakash.shinghal1993@gmail.com
          JIRA_PROJECT: STOC
          JIRA_ISSUE_TYPE: Bug
          JIRA_WATCHERS: aakash.shinghal1993@gmail.com
