name: Raising JIRA issues for Dependabot alerts

on:
  schedule:
    - cron: '0 0 1 * *'  
  workflow_dispatch:

jobs:
  syncSecurityAlerts:
    runs-on: self-hosted
    steps:
      - name: "Sync security alerts to Jira issues"
        uses: reload/github-security-jira@v1.3.1
        env:
          GH_SECURITY_TOKEN: ${{ secrets.GitHubSecurityToken }}
          JIRA_TOKEN: ${{ secrets.JiraApiToken }}
          JIRA_HOST: https://cruzeaakash.atlassian.net
          JIRA_USER: ${{ secrets.UserId }}
          JIRA_PROJECT: SM
          JIRA_ISSUE_TYPE: Bug
